[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuración correcta para plugins
[[plugins]]
package = "netlify-plugin-nextjs"
  [plugins.inputs]
  enable = false