[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Deshabilitar el plugin de Next.js
[plugins]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = false